### ISSUE TITLE
`await` does not return until the terminal is moved

### ISSUE THREAD

**Issue by sivabudh** [dynamsoft-dbr/linux-barcode-sdk-node-wrapper#3]
@yushulx I re-wrote the code like this:

**main.js**
```
// Express
const express = require('express');
const app = express();

// Lodash
const _ = require('lodash');

// DBR
const dbr = require('./build/Release/dbr');
dbr.initLicense("t0068MgAAAGvV3VqfqOzkuVGi7x/PFfZUQoUyJOakuduaSEoI2Pc8+kMwjrojxQgE5aJphmhagRmq/S9lppTkM4w3qCQezxk=");

// Promisify
const {promisify} = require('util');
const decodeFilePromise = promisify(dbr.decodeFileAsync);

app.get('/', async (req, res) => {
    console.log("Received a barcode scan request!");
    try {
        const oneDimensionType = 0x3FF;
        const scannedResults = await decodeFilePromise('test.jpg', oneDimensionType);

        const imeiResults = _.uniq(_.map(_.filter(scannedResults, ['format', 'CODE_128']), 'value'));
        console.log(`Successfully scanned the image: ${imeiResults}`);

        res.send(`IMEI results: ${imeiResults}`);
    }
    catch (err) {
        console.log(`Failed to scan the image: ${err}`);
        res.send('Could not scan the barcode!');
    }
});

app.listen(3000, () => {
    console.log('Example app listening on port 3000!');
});
```

Reference (forked from your repo):
https://github.com/sivabudh/linux-barcode-sdk-node-wrapper/blob/dbr-async-await/main.js

From the outset, it should have worked fine, right? But what I found was that `await` never returned until I moved the Terminal screen (!!). If this is unclear, please kindly see the GIF below.

GIF demonstrating the problem:
https://cl.ly/mcb6

**Comment by sivabudh** [comment]
@yushulx 

I posted the same question on StackOverflow, and got an interesting comment. 

> Resizing a terminal sends particular signals to a process. Perhaps the library you're using relies on those, for some reason. However, it's hard to say without the library code; is that available from somewhere?

Ref: https://stackoverflow.com/questions/46321805/strange-node-await-never-unblocks?noredirect=1#comment79606664_46321805

**Comment by yushulx** [comment]
@sivabudh it seems to be a known Express issue. https://github.com/tjanczuk/edge/issues/325. I can do nothing with my code. I've tested your code and found when the libuv work's done, it blocked. Once you do something, such as refresh your page or send interruption signal in the terminal, the code will continue to run.  

I suggest that you can use the traditional way as follows:

```
// Express
const express = require('express');
const app = express();

// Lodash
const _ = require('lodash');

// DBR
const dbr = require('./build/Release/dbr');
dbr.initLicense(
    "t0068MgAAAGvV3VqfqOzkuVGi7x/PFfZUQoUyJOakuduaSEoI2Pc8+kMwjrojxQgE5aJphmhagRmq/S9lppTkM4w3qCQezxk=");

// Promisify
const {promisify} = require('util');
const decodeFilePromise = promisify(dbr.decodeFileAsync);

app.get('/', (req, res) => {
  console.log("Received a barcode scan request!");
  try {
    const oneDimensionType = 0x3FF;
    dbr.decodeFileAsync('test.jpg', 0x3FF, (err, scannedResults) => {
        console.log(scannedResults);

      const imeiResults = _.uniq(
          _.map(_.filter(scannedResults, ['format', 'CODE_128']), 'value'));
      console.log(`Successfully scanned the image: ${imeiResults}`);
      res.send(`IMEI results: ${imeiResults}`);
    });

  } catch (err) {
    console.log(`Failed to scan the image: ${err}`);
    res.send('Could not scan the barcode!');
  }
});

app.listen(3000, () => { console.log('Example app listening on port 3000!'); });

```

**Comment by sivabudh** [comment]
@yushulx If that's the case, I'm thinking about dropping Express, and use some other framework. I probably will use a similar bare bone framework. I will update you.
