### ISSUE TITLE
Misleading comment in test.js

### ISSUE THREAD

**Issue by cjus** [dynamsoft-dbr/linux-barcode-sdk-node-wrapper#4]
In the test.js source file the following declaration exist:

```javascript
var barcodeTypes = 0x3FF | 0x2000000 | 0x8000000 |
                   0x4000000;  // 1D, QRCODE, PDF417, DataMatrix
```

I think the comment may be misleading as `PDF417` does not correspond to `0x8000000` according to the [DynamsoftBarcodeReader.h](https://github.com/dynamsoft-dbr/linux-barcode-sdk-node-wrapper/blob/master/DynamsoftBarcodeReader.h#L148) file which lists:

BF_DATAMATRIX = 0x8000000

The test.js line should read: 

```javascript
var barcodeTypes = 0x3FF | 0x2000000 | 0x8000000 | 0x4000000;  // 1D, QRCODE, DataMatrix, PDF417
```

or reordered as:

```javascript
var barcodeTypes = 0x3FF | 0x2000000 | 0x4000000 | 0x8000000;  // 1D, QRCODE, PDF417, DataMatrix
```

Granted when OR'ed together the value of barcodeTypes remain the same. The issue I ran into was mistakenly thinking that DataMatrix could be specified using 0x4000000.

**Comment by yushulx** [comment]
Sorry for misleading you. It's fixed now.
